# Generated by Django 5.2.7 on 2026-02-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
    ]
